"""Runic command-line entry point — wires the full pipeline together."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from rich.console import Console

from .config import ConfigError, load_spotify_credentials
from .effort import build_effort_timeline
from .gpx import parse_route
from .matcher import Weights, build_playlist
from .models import PlaylistEntry, Song
from .output import print_table, write_output
from .pace import build_pace_model
from .reccobeats import fetch_songs
from .spotify_client import collect_candidate_ids
from .spotify_oauth import (
    add_tracks,
    create_playlist,
    get_current_user_id,
    get_user_access_token,
)


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="runic",
        description="Generate a terrain-matched running playlist from a GPX route.",
    )
    p.add_argument("--gpx", required=True, help="Route GPX file to run.")
    p.add_argument("--pb", action="append", default=[],
                   help="Personal best, e.g. --pb 5k=22:30 (repeatable).")
    p.add_argument("--past-run", action="append", default=[], dest="past_run",
                   help="Past-run GPX for measured pace/cadence (repeatable).")
    p.add_argument("--cadence", type=float, default=None,
                   help="Override target cadence in steps/min (e.g. 175).")

    # Candidate song pool: live Spotify OR offline JSON.
    p.add_argument("--playlist", action="append", default=[],
                   help="Public Spotify playlist URL/URI/id (repeatable).")
    p.add_argument("--candidates-json", default=None,
                   help="Offline candidate pool (skips Spotify/ReccoBeats).")
    p.add_argument("--save-candidates", default=None,
                   help="Save the fetched candidate pool to this JSON for reuse.")

    # Tuning knobs.
    p.add_argument("--segment-length", type=float, default=200.0,
                   help="Terrain segment length in metres (default 200).")
    p.add_argument("--w-tempo", type=float, default=0.5, help="Tempo weight.")
    p.add_argument("--w-energy", type=float, default=0.4, help="Energy weight.")
    p.add_argument("--tempo-tol", type=float, default=12.0,
                   help="Tempo match tolerance in BPM.")

    p.add_argument("--out", default=None, help="Write playlist to .csv or .json.")

    # Create the playlist in your Spotify account (user login required).
    p.add_argument("--create-playlist", default=None, metavar="NAME",
                   help="Create this playlist in your Spotify account.")
    p.add_argument("--private", action="store_true",
                   help="Make the created playlist private (default: public).")
    p.add_argument("--auth-port", type=int, default=8888,
                   help="Local port for the OAuth redirect (default 8888).")
    return p


def _create_spotify_playlist(
    entries: list[PlaylistEntry], name: str, *, public: bool, port: int,
    console: Console,
) -> None:
    """Push the ordered playlist into the user's Spotify account."""
    creds = load_spotify_credentials()
    token = get_user_access_token(creds, port=port)
    user_id = get_current_user_id(token)
    desc = "Generated by Runic — terrain-matched running playlist."
    playlist_id, url = create_playlist(
        token, user_id, name, public=public, description=desc
    )
    add_tracks(token, playlist_id, [e.song.spotify_id for e in entries])
    console.print(
        f"[green]Created playlist '{name}' "
        f"({len(entries)} tracks)[/green] -> {url or playlist_id}"
    )


def _load_candidates_json(path: str | Path) -> list[Song]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    songs: list[Song] = []
    for d in data:
        songs.append(
            Song(
                spotify_id=d.get("spotify_id", ""),
                reccobeats_id=d.get("reccobeats_id", d.get("spotify_id", "")),
                title=d.get("title", "Unknown"),
                artists=tuple(d.get("artists", ("Unknown",))),
                duration_ms=int(d.get("duration_ms", 0)),
                tempo=float(d.get("tempo", 0.0)),
                energy=float(d.get("energy", 0.0)),
                valence=float(d.get("valence", 0.0)),
                danceability=float(d.get("danceability", 0.0)),
                loudness=float(d.get("loudness", 0.0)),
            )
        )
    return songs


def _save_candidates_json(songs: list[Song], path: str | Path) -> None:
    payload = [
        {
            "spotify_id": s.spotify_id,
            "reccobeats_id": s.reccobeats_id,
            "title": s.title,
            "artists": list(s.artists),
            "duration_ms": s.duration_ms,
            "tempo": s.tempo,
            "energy": s.energy,
            "valence": s.valence,
            "danceability": s.danceability,
            "loudness": s.loudness,
        }
        for s in songs
    ]
    Path(path).write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _gather_songs(args, console: Console) -> tuple[list[Song], int]:
    """Return (candidate_songs, skipped_count) from offline JSON or live APIs."""
    if args.candidates_json:
        songs = _load_candidates_json(args.candidates_json)
        console.print(f"[dim]Loaded {len(songs)} candidates (offline).[/dim]")
        return songs, 0

    if not args.playlist:
        raise ConfigError(
            "No song source. Pass --playlist <public url> "
            "or --candidates-json <file> for offline mode."
        )

    spotify_ids = collect_candidate_ids(args.playlist)
    console.print(f"[dim]Collected {len(spotify_ids)} tracks from playlists.[/dim]")
    songs, skipped = fetch_songs(spotify_ids)
    console.print(
        f"[dim]Resolved {len(songs)} songs via ReccoBeats "
        f"({len(skipped)} not in catalogue).[/dim]"
    )
    if args.save_candidates:
        _save_candidates_json(songs, args.save_candidates)
        console.print(f"[dim]Saved candidate pool -> {args.save_candidates}[/dim]")
    return songs, len(skipped)


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    console = Console()

    try:
        route = parse_route(args.gpx, segment_length_m=args.segment_length)
        console.print(
            f"[dim]Route: {route.total_distance_m / 1000:.2f} km, "
            f"+{route.total_ascent_m:.0f} m / -{route.total_descent_m:.0f} m, "
            f"{len(route.segments)} segments.[/dim]"
        )

        model = build_pace_model(
            pbs=args.pb or None,
            past_run_gpx=args.past_run or None,
            target_distance_m=route.total_distance_m,
            cadence_override=args.cadence,
        )
        slots, total_s = build_effort_timeline(route, model)

        songs, skipped = _gather_songs(args, console)
        if not songs:
            console.print("[red]No candidate songs available — nothing to build.[/red]")
            return 1

        weights = Weights(tempo=args.w_tempo, energy=args.w_energy,
                          tempo_tolerance=args.tempo_tol)
        entries = build_playlist(slots, total_s, songs, weights=weights)

        print_table(entries, total_s, skipped=skipped, console=console)
        if args.out:
            write_output(entries, args.out)
            console.print(f"[green]Wrote {args.out}[/green]")
        if args.create_playlist:
            _create_spotify_playlist(
                entries, args.create_playlist,
                public=not args.private, port=args.auth_port, console=console,
            )
        return 0

    except (ConfigError, FileNotFoundError, ValueError, RuntimeError) as exc:
        console.print(f"[red]Error:[/red] {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
