"""YouTube Music export for Runic.

Takes the terrain-ordered tracks Runic selected (each known by title, artist and
its Spotify duration) and re-resolves them to YouTube Music catalogue songs, then
creates a playlist preserving the order.

The catch this module solves: Spotify track ids mean nothing to YouTube, so every
track has to be *re-found* by searching YT Music. Search returns variants (live,
remix, instrumental, covers, sped-up edits), so we score candidates and auto-pick
the best, using the original Spotify duration as an anchor to reject wrong-length
matches.

Searching works unauthenticated. Creating a playlist needs the user's YT Music
auth file (see README / ``ytmusicapi`` setup); point ``RUNIC_YTMUSIC_AUTH`` at it.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass

# Variant keywords we down-rank unless the original track title also has them.
_NEGATIVE = (
    "remix", "instrumental", "cover", "live", "8-bit", "8 bit", "tribute",
    "sped up", "slowed", "reverb", "karaoke", "nightcore", "loop", "mashup",
    "acoustic", "rework", "edit", "version",
)


def _norm(s: str) -> str:
    """Lowercase, drop feat./parenthetical noise and punctuation for comparison."""
    s = (s or "").lower()
    s = re.sub(r"\(feat[^)]*\)|feat\.?[^,\-]*", " ", s)
    s = re.sub(r"[^a-z0-9 ]+", " ", s)
    return re.sub(r"\s+", " ", s).strip()


@dataclass
class Match:
    title: str          # original (Spotify) title
    artist: str         # original (Spotify) artist
    video_id: str | None
    yt_title: str | None
    score: float


def _score(track_title: str, track_artist: str, dur_s: float | None, cand: dict) -> float:
    """Higher is better. Combines title overlap, artist match and a duration anchor."""
    qt, ct = _norm(track_title), _norm(cand.get("title", ""))
    qa = _norm(track_artist)
    ca = " ".join(_norm(a.get("name", "")) for a in (cand.get("artists") or []))

    score = 0.0

    # Title token overlap (0..2).
    qtoks, ctoks = set(qt.split()), set(ct.split())
    if qtoks:
        score += 2.0 * len(qtoks & ctoks) / len(qtoks)

    # Artist match (any meaningful token of the query artist appears).
    if qa and any(tok in ca for tok in qa.split() if len(tok) > 2):
        score += 1.5

    # Duration anchor — the strongest signal for rejecting wrong variants.
    cd = cand.get("duration_seconds")
    if dur_s and cd:
        diff = abs(cd - dur_s)
        if diff <= 3:
            score += 1.5
        elif diff <= 7:
            score += 0.8
        elif diff > 20:
            score -= 1.5

    # Penalise undesired variants the original didn't ask for.
    low = (cand.get("title") or "").lower()
    orig = (track_title or "").lower()
    for kw in _NEGATIVE:
        if kw in low and kw not in orig:
            score -= 1.2

    return score


def match_tracks(yt, tracks: list[dict]) -> list[Match]:
    """Resolve each ``{title, artist, duration_s}`` to a YT Music videoId."""
    matches: list[Match] = []
    for t in tracks:
        query = f"{t.get('title', '')} {t.get('artist', '')}".strip()
        try:
            results = yt.search(query, filter="songs", limit=5)
        except Exception:
            results = []
        best, best_s = None, float("-inf")
        for cand in results:
            s = _score(t.get("title", ""), t.get("artist", ""), t.get("duration_s"), cand)
            if s > best_s:
                best, best_s = cand, s
        if best and best.get("videoId"):
            matches.append(
                Match(t.get("title", ""), t.get("artist", ""),
                      best["videoId"], best.get("title"), best_s)
            )
        else:
            matches.append(Match(t.get("title", ""), t.get("artist", ""), None, None, 0.0))
    return matches


def get_client(auth_path: str | None = None):
    """Return an authenticated YTMusic client, or raise with a helpful message."""
    from ytmusicapi import YTMusic  # lazy: keep import cost/failure out of app startup

    auth_path = auth_path or os.environ.get("RUNIC_YTMUSIC_AUTH", "browser.json")
    if not os.path.exists(auth_path):
        raise RuntimeError(
            f"YT Music auth file not found at '{auth_path}'. Run a one-time setup "
            "(`ytmusicapi browser` to create browser.json) and set RUNIC_YTMUSIC_AUTH "
            "if it lives elsewhere."
        )
    return YTMusic(auth_path)


def create_playlist(yt, title: str, video_ids: list[str], description: str = "") -> str:
    """Create a private YT Music playlist with the given videos, return its id."""
    result = yt.create_playlist(
        title,
        description or "Generated by Runic — terrain-matched run playlist.",
        privacy_status="PRIVATE",
        video_ids=video_ids,
    )
    if isinstance(result, dict):
        return result.get("id") or result.get("playlistId") or ""
    return result
